# .github/workflows/simple_example.yaml        #  <- location of the yaml file in your project  
on: push                                       #  <- define when the Action will run
jobs:
  run:
    runs-on: ubuntu-latest                     #  <- can be linux, windows, macos
    name: Run treebeard                        #  <- name your job (there can be multiple)
    steps:
      - uses: actions/checkout@v2              #  <- gets your repo code
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8          #  <- installs python
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: foo
          environment-file: environment.yml
          python-version: 3.8
          channels: conda-forge
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: true
          use-only-tar-bz2: true    
      - uses: treebeardtech/treebeard@master   #  <- runs Treebeard
        with:
          use-docker: false
