name: Execute notebook

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Install conda environment
      uses: conda-incubator/setup-miniconda@v1
      with:
        activate-environment: jupyter-actions
        environment-file: environment.yml
        python-version: 3.7
          
    - name: Execute all Notebooks
      shell: bash -l {0}
      run: |
        conda activate jupyter-actions
        pytest
