# .github/workflows/simple_example.yaml        #  <- location of the yaml file in your project  
on: push                                       #  <- define when the Action will run
jobs:
  run:
    runs-on: ubuntu-latest                     #  <- can be linux, windows, macos
    name: Run treebeard                        #  <- name your job (there can be multiple)
    steps:
      - uses: actions/checkout@v2              #  <- gets your repo code
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8          #  <- installs python
      - run: pip install pandas numpy matplotlib
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: r-environment
      - name: Bash
        shell: bash -l {0}
        run: |
          conda info
          conda install r-rlang=0.3.4 pandas=1.1.3 numpy=1.19.2 matplotlib=3.3.2 nbconvert=6.0.7 notebook=6.1.4 python=3.8.5 r-caret=6.0_83 r-data.table=1.12.2 r-irkernel=0.8.15 r-tidyverse=1.2.1
          conda list
          jupyter nbconvert --to notebook --execute test_notebook_convert.ipynb
          jupyter nbconvert --ExecutePreprocessor.kernel_name=ir --to notebook --execute '.\Covid EDA.ipynb'
          git add .
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: main
      - uses: treebeardtech/treebeard@master   #  <- runs Treebeard
        with:
          use-docker: false
