# .github/workflows/simple_example.yaml        #  <- location of the yaml file in your project  
on: push                                       #  <- define when the Action will run
jobs:
  run:
    runs-on: ubuntu-latest                     #  <- can be linux, windows, macos
    name: Run treebeard                        #  <- name your job (there can be multiple)
    steps:
      - uses: actions/checkout@v2              #  <- gets your repo code
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8          #  <- installs python
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: r-environment
      - name: Bash
        shell: bash -l {0}
        run: |
          conda info
          conda install r-rlang=0.3.4 pandas=1.1.3 numpy=1.19.2
          conda list
      - uses: treebeardtech/treebeard@master   #  <- runs Treebeard
        with:
          use-docker: false
